In [32]:
# Assignment 1

# keys for users_dictionary
keys=['name','age','work','skills','degree','salary']

# user dictionary
users_dictionary = {}

# skills list
skills_list=[]

# degree_dictionary
degree_dictionary = {}

# degree keys_list
degree_keys = ['title','major','completionDate']

# dictionary_lists
dictionary_list = []

users=0

for total_user in range(int(input("How many users you want to add? "))):
    print("\nUser "+str(users+1))
    for x in range(len(keys)):
        # getting age in integer
        if keys[x] == 'age':
            users_dictionary[keys[x]] = int(input("Enter " + keys[x] + ": "))
        # getting skills in a list
        elif keys[x] == 'skills':
            total_skills = int(input("How many skills you have? "))
            for skills in range(total_skills):
                skills_list.insert(skills,input("Enter skill " + str(skills+1) + ": "))
            users_dictionary[keys[x]] = skills_list
            skills_list=[]
        # getting degree in a dictionary
        elif keys[x] == 'degree':
            for degree_no in range(len(degree_keys)):
                degree_dictionary[degree_keys[degree_no]] = input("Enter degree " + degree_keys[degree_no] + ": ")
            users_dictionary[keys[x]] = degree_dictionary
            degree_dictionary={}
        # getting salary in integer
        elif keys[x] == 'salary':
            users_dictionary[keys[x]] = int(input("Enter " + keys[x] + ": "))
        # saving other keys and values
        else:
            users_dictionary[keys[x]] = input("Enter " + keys[x] + ": ")
    dictionary_list.insert(users,users_dictionary)
    users_dictionary={}
    users +=1

How many users you want to add? 3

User 1
Enter name: Hamza Ali
Enter age: 25
Enter work: A.I
How many skills you have? 3
Enter skill 1: python
Enter skill 2: tensorflow
Enter skill 3: cloud
Enter degree title: BS
Enter degree major: computer Science
Enter degree completionDate: Jun 2019
Enter salary: 259999

User 2
Enter name: Farooq Aziz
Enter age: 27
Enter work: Cloud Native
How many skills you have? 3
Enter skill 1: ubuntu
Enter skill 2: docker
Enter skill 3: kubernetes
Enter degree title: MS
Enter degree major: Software engineer
Enter degree completionDate: May 2018
Enter salary: 200000

User 3
Enter name: Abu Bakr
Enter age: 30
Enter work: Blockchain
How many skills you have? 3
Enter skill 1: BS
Enter skill 2: computer Science
Enter skill 3: Ethereum
Enter degree title: BS
Enter degree major: computer Science
Enter degree completionDate: May 2019
Enter salary: 300000

In [33]:
dictionary_list

[{'name': 'Hamza Ali',
  'age': 25,
  'work': 'A.I',
  'skills': ['python', 'tensorflow', 'cloud'],
  'degree': {'title': 'BS',
   'major': 'computer Science',
   'completionDate': 'Jun 2019'},
  'salary': 259999},
 {'name': 'Farooq Aziz',
  'age': 27,
  'work': 'Cloud Native',
  'skills': ['ubuntu', 'docker', 'kubernetes'],
  'degree': {'title': 'MS',
   'major': 'Software engineer',
   'completionDate': 'May 2018'},
  'salary': 200000},
 {'name': 'Abu Bakr',
  'age': 30,
  'work': 'Blockchain',
  'skills': ['BS', 'computer Science', 'Ethereum'],
  'degree': {'title': 'BS',
   'major': 'computer Science',
   'completionDate': 'May 2019'},
  'salary': 300000}]

In [3]:
# Assignment 2

# print method 1
print('this program will find the table of all numbers, which are given in the range')
for x in range(int(input('Enter number from where to start: ')),int(input('Enter number at where to end: '))+1):
    for inc in range(1,11):
        print(str(x) + ' x ' + str(inc) + " = " + str(x*inc))
    print('\n')

this program will find the table of all numbers, which are given in the range
Enter number from where to start: 5
Enter number at where to end: 10
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60


7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70


8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80


9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90


10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 = 80
10 x 9 = 90
10 x 10 = 100

In [1]:
# print method 2

print('this program will find the table of all numbers, which are given in the range')
f=int(input('Enter number from where to start: '))
l=int(input('Enter number at where to end: '))
for inc in range(1,11):
    for x in range(f,l+1):
        print(str(x) + ' x ' + str(inc) + " = " + str(x*inc), end='\t')
    print('\n')

this program will find the table of all numbers, which are given in the range
Enter number from where to start: 5
Enter number at where to end: 10
5 x 1 = 5	6 x 1 = 6	7 x 1 = 7	8 x 1 = 8	9 x 1 = 9	10 x 1 = 10

5 x 2 = 10	6 x 2 = 12	7 x 2 = 14	8 x 2 = 16	9 x 2 = 18	10 x 2 = 20

5 x 3 = 15	6 x 3 = 18	7 x 3 = 21	8 x 3 = 24	9 x 3 = 27	10 x 3 = 30

5 x 4 = 20	6 x 4 = 24	7 x 4 = 28	8 x 4 = 32	9 x 4 = 36	10 x 4 = 40

5 x 5 = 25	6 x 5 = 30	7 x 5 = 35	8 x 5 = 40	9 x 5 = 45	10 x 5 = 50

5 x 6 = 30	6 x 6 = 36	7 x 6 = 42	8 x 6 = 48	9 x 6 = 54	10 x 6 = 60

5 x 7 = 35	6 x 7 = 42	7 x 7 = 49	8 x 7 = 56	9 x 7 = 63	10 x 7 = 70

5 x 8 = 40	6 x 8 = 48	7 x 8 = 56	8 x 8 = 64	9 x 8 = 72	10 x 8 = 80

5 x 9 = 45	6 x 9 = 54	7 x 9 = 63	8 x 9 = 72	9 x 9 = 81	10 x 9 = 90

5 x 10 = 50	6 x 10 = 60	7 x 10 = 70	8 x 10 = 80	9 x 10 = 90	10 x 10 = 100